# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
    paths:
      - 'stellaris/gradle.properties'


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checks-out 
      - uses: actions/checkout@v2

      - name: Build jar
        run: |
          chmod +x ./gradlew
          ./gradlew jar
      - name: Publish to the github packages Repository
        run: ./gradlew publish

