

name: Publish package to GitHub Packages
on:
  push:
    branches: [ master ]
    paths:
      - 'gradle.properties'
jobs:
  publish:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2

      - name: Build jar
        run: |
          chmod +x ./gradlew
          ./gradlew jar
      - name: Publish to the github packages Repository
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
